package net.csgrebo.mccontrol.config;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.LoggerContext;
import ch.qos.logback.classic.encoder.PatternLayoutEncoder;
import ch.qos.logback.classic.spi.Configurator;
import ch.qos.logback.classic.tyler.TylerConfiguratorBase;
import ch.qos.logback.core.ConsoleAppender;
import ch.qos.logback.core.rolling.RollingFileAppender;
import ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy;

/**
 *
 * <p>This file was generated by logback-tyler version 1.0.4</p>
 *
 * <p>Eventual errors and warnings are appended at the end.</p>
 *
 * <p>You may experiment with logback.xml to Java translation, i.e.
 * TylerConfigurator generation, at the following URL:</p>
 *
 * <p>     https://logback.qos.ch/translator/services/xml2Java.html </p>
 *
 * <p>This generated TylerConfigurator class is intended to be copied and integrated
 * into the user's project as a custom configurator. It will configure logback
 * without XML. You are free to rename TylerConfigurator as you wish.</p>
 *
 * <p>It requires logback-classic version 1.5.20 or later at runtime.</p>
 *
 * <p>Custom configurators are looked up via Java's service-provide facility. If a
 * custom provider is found, it takes precedence over logback's own configurators,
 * e.g. DefaultJoranConfigurator.</p>
 *
 * <p>To install your custom configurator to your project, add a
 * provider-configuration file to the following path:</p>
 *
 * <pre>  META-INF/services/ch.qos.logback.classic.spi.Configurator</pre>
 *
 * <p>This provider-configuration file should contain a line with the fully
 * qualified class name of your tyler configurator.</p>
 *
 * <p>See also item 1 of 'Configuration at initialization' section at </p>
 *
 * <p>  https://logback.qos.ch/manual/configuration.html#auto_configuration</p>
 *
 * <p>Configurations using TylerConfigurator can still dynamically configure
 * logger levels with the help of properties files. Moreover, configuration
 * files in properties format can be watched for changes. See the
 * documentation on PropertiesConfigurator for more details.</p>
 *
 * <p>https://logback.qos.ch/manual/configuration.html#propertiesConfigurator</p>
 *
 * <p>Please note that when logback-tyler transforms XML to Java, it performs
 * runtime analysis of classes using Java's class reflection. Thus,
 * if your logback.xml mentions classes which are unavailable on the classpath,
 * logback-tyler will fail during the translation.</p>
 *
 */
public class TylerConfigurator extends TylerConfiguratorBase implements Configurator {

    private static TylerConfigurator INSTANCE;

    public static TylerConfigurator getInstance() {
        if (INSTANCE == null) {
            new TylerConfigurator();
        }
        return INSTANCE;
    }

    public TylerConfigurator() {
        INSTANCE = this;
    }

    /**
     * Appender variable referencing the appender named "FILE".
     */
    protected RollingFileAppender appenderFILE;

    /**
     * Appender variable referencing the appender named "STDOUT".
     */
    protected ConsoleAppender appenderSTDOUT;

    protected Logger logger_ROOT;

    /**
     * <p>This method performs configuration per {@link Configurator} interface.</p>
     *
     * <p>If <code>TylerConfigurator</code> is installed as a configurator service, this
     * method will be called by logback-classic during initialization.</p>
     */
    @Override
    public Configurator.ExecutionStatus configure(LoggerContext loggerContext) {
        setContext(loggerContext);
        this.appenderSTDOUT = setupAppenderSTDOUT();
        this.appenderFILE = setupAppenderFILE();
        logger_ROOT = setupLogger("ROOT", "WARN", null);
        logger_ROOT.addAppender(appenderSTDOUT);
        logger_ROOT.addAppender(appenderFILE);
        return ExecutionStatus.DO_NOT_INVOKE_NEXT_IF_ANY;
    }

    ConsoleAppender setupAppenderSTDOUT() {
        ConsoleAppender appender = new ConsoleAppender();
        appender.setContext(context);
        appender.setName("STDOUT");

        // Configure component of type PatternLayoutEncoder
        PatternLayoutEncoder patternLayoutEncoder = new PatternLayoutEncoder();
        patternLayoutEncoder.setContext(context);
        patternLayoutEncoder.setPattern("%-4relative [%thread] %-5level %logger{35} -%kvp- %msg %n");
        patternLayoutEncoder.setParent(appender);
        patternLayoutEncoder.start();
        // Inject component of type PatternLayoutEncoder into parent
        appender.setEncoder(patternLayoutEncoder);

        appender.start();
        return appender;
    }

    RollingFileAppender setupAppenderFILE() {
        RollingFileAppender appender = new RollingFileAppender();
        appender.setContext(context);
        appender.setName("FILE");
        appender.setFile("log/rcon-client.log");

        // Configure component of type SizeAndTimeBasedRollingPolicy
        SizeAndTimeBasedRollingPolicy sizeAndTimeBasedRollingPolicy = new SizeAndTimeBasedRollingPolicy();
        sizeAndTimeBasedRollingPolicy.setContext(context);
        sizeAndTimeBasedRollingPolicy.setFileNamePattern("log/archive/rcon-client-%d{yyyy-MM-dd}.%i.log.gz");
        sizeAndTimeBasedRollingPolicy.setMaxFileSize(ch.qos.logback.core.util.FileSize.valueOf("100MB"));
        sizeAndTimeBasedRollingPolicy.setMaxHistory(60);
        sizeAndTimeBasedRollingPolicy.setTotalSizeCap(ch.qos.logback.core.util.FileSize.valueOf("20GB"));
        sizeAndTimeBasedRollingPolicy.setParent(appender);
        sizeAndTimeBasedRollingPolicy.start();
        // Inject component of type SizeAndTimeBasedRollingPolicy into parent
        appender.setRollingPolicy(sizeAndTimeBasedRollingPolicy);

        // Configure component of type PatternLayoutEncoder
        PatternLayoutEncoder patternLayoutEncoder = new PatternLayoutEncoder();
        patternLayoutEncoder.setContext(context);
        patternLayoutEncoder.setPattern("%msg%n");
        patternLayoutEncoder.setParent(appender);
        patternLayoutEncoder.start();
        // Inject component of type PatternLayoutEncoder into parent
        appender.setEncoder(patternLayoutEncoder);

        appender.start();
        return appender;
    }

    public void updateLogLevel(Level level) {
        logger_ROOT.setLevel(level);
    }
}
